Web portal
magnetarpulse/neurobazaar pull request #22
Opened 2024-08-19 15:57 UTC by Guptavivek27

2024-08-21 16:59 UTC, alexandru-orhean requested changes
Please update the readme so that it's more in line with the readme from the experimental branch.

2024-08-21 16:59 UTC, alexandru-orhean commented on README.md
> +This software has been developed and tested on Ubuntu **22.04 LTS**.
You need to add information about the GCC compiler as well.

2024-08-21 16:59 UTC, alexandru-orhean commented on README.md
> +https://github.com/nvm-sh/nvm
This is not a Ubuntu dependency. Please include the Node.js instructions in a different section. The instructions should be placed after install the Ubuntu dependencies.

2024-08-21 16:59 UTC, alexandru-orhean commented on README.md
> +Load/activate the Python Virtual Environment in Ubuntu 22.04 LTS:
We already mentioned that we only support Ubuntu 22.04 LTS Server Edition. Mentioning it again is not required.

2024-08-21 16:59 UTC, alexandru-orhean commented on README.md
> -```
The readme from the experimental branch is more up to date. Please include those instructions.

2024-08-22 02:06 UTC, Guptavivek27 commented
> Please update the readme so that it's more in line with the readme from the experimental branch.

Updates done.  Please proceed with the merge.

2024-09-13 18:45 UTC, alexandru-orhean approved these changes
Looks good to me!

2024-09-13 18:45 UTC, merged